Soluções Web/Cinema/config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  devise_for :users

  root to: 'welcome#index'

  resources :theaters do
    resources :rooms do
      resources :sessions
    end
    resources :sessions
  end

  resources :baskets, only: :show
  post '/baskets/:id', to: 'baskets#confirm'
  get '/baskets/:id/finished', to: 'baskets#finished'

  get '/movie/sessions/:id/choose_seat', to: 'sessions#choose_seat'
  post '/movie/sessions/:id/choose_seat', to: 'sessions#buy'

  namespace :admin do
    root 'welcome#index'

    resources :theaters do
      resources :rooms do
        resources :sessions
      end
    end

    resources :movies do
      resources :sessions
    end

    resources :sessions
  end
end

Soluções Web/Cinema/app/models/basket.rb
class Basket < ActiveRecord::Base
  belongs_to :customer
  has_many :tickets
end

Soluções Web/Cinema/app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Soluções Web/Cinema/app/models/movie.rb
class Movie < ActiveRecord::Base
    has_many :sessions
    validates :name , presence: true
    validates :summary , presence: true
    validates :debut , presence: true
end

Soluções Web/Cinema/app/models/room.rb
class Room < ActiveRecord::Base
    belongs_to :theater
    has_many :sessions
    validates :name , presence: true
    validates :rows , presence: true
    validates :seats_per_row , presence: true
end

Soluções Web/Cinema/app/models/session.rb
class Session < ActiveRecord::Base
  belongs_to :room
  belongs_to :movie
  has_many :tickets
  validates :datetime , presence: true
end

Soluções Web/Cinema/app/models/theater.rb
class Theater < ActiveRecord::Base
    has_many :rooms
    validates :name , presence: true , length: { minimum: 5 }
    validates :address , presence: true
    validates :address_number , presence: true
    validates :city , presence: true
    validates :state , presence: true
end

Soluções Web/Cinema/app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :session
  belongs_to :basket
end

Soluções Web/Cinema/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Soluções Web/Cinema/app/controllers/admin/movies_controller.rb
class Admin::MoviesController < Admin::ApplicationController
    def index
        @movies = Movie.all
    end

    def show
        @movie = Movie.find(params[:id])
    end

    def new
        @movie = Movie.new
    end

    def create
        @movie = Movie.new(movie_params)
        if @movie.save
            redirect_to @movie
        else
            render 'new'
        end
    end

    def edit
        @movie = Movie.find(params[:id])
    end

    def update
        @movie = Movie.find(params[:id])

        if @movie.update(movie_params)
            redirect_to movies_path
        else
            render 'edit'
        end
    end

    private
    def movie_params
        params.require(:movie).permit(:name, :summary, :debut)
    end
end

Soluções Web/Cinema/app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < Admin::ApplicationController
    def index
        @theater = Theater.find(params[:theater_id])
        @rooms = @theater.rooms
    end

    def show
        @theater = Theater.find(params[:theater_id])
        @room = Room.find(params[:id])
    end

    def new
        @theater = Theater.find(params[:theater_id])
        @room = Room.new
    end

    def create
        @theater = Theater.find(params[:theater_id])
        @room = @theater.rooms.create(room_params)

        redirect_to admin_theater_path(@theater)
    end

    def edit
        @theater = Theater.find(params[:theater_id])
        @room = Room.find(params[:id])
    end

    def update
        @theater = Theater.find(params[:theater_id])
        @room = Room.find(params[:id])

        if @room.update(room_params)
            redirect_to admin_theater_rooms_path(@theater)
        else
            render 'edit'
        end
    end

    def destroy
        @theater = Theater.find(params[:theater_id])
        @room = Room.find(params[:id])
        @room.destroy
        redirect_to admin_theater_rooms_path(@theater)
    end

    private
    def room_params
        params.require(:room).permit(:name, :rows, :seats_per_row)
    end
end

Soluções Web/Cinema/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Soluções Web/Cinema/app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  def show
    @basket = Basket.find(params[:id])
    @tickets = Ticket.where(basket: @basket.id)
  end

  def confirm
    if params[:confirmed].nil?
      basket = Basket.find(params[:id])
      basket.destroy

      redirect_to root_path
    elsif customer_signed_in?
      basket = Basket.find(params[:id])
      basket.customer = current_customer
      basket.save

      redirect_to "/baskets/" + basket.id.to_s + "/finished"
    else
      redirect_to new_customer_session_path
    end
  end

  def finished
    @basket = Basket.find(params[:id])
  end
end

Soluções Web/Cinema/app/controllers/movie_sessions_controller.rb
class MovieSessionsController < ApplicationController
    def choose_seat
        @session = movie_sessionsSession.find(params[:id])
        @room = @session.room
        @theater = @room.theater
        @movie = @session.movie
    end

    def buy
        session = Session.find(params[:id])
        seats = params[:ticket_seats]

        selected_seats = []
        seats.keys.each do |seat|
            if params[:ticket_seats][seat] == "1"
                selected_seats << seat.split(",")
            end
        end

        basket = Basket.new
        basket.save

        selected_seats.each do |seat|
            Ticket.create(:session => session, :basket => basket, :row => seat[0], :seat => seat[1] )
        end

        redirect_to basket_path(basket)
    end
end

Soluções Web/Cinema/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def choose_seat
        @session = Session.find(params[:id])
        @room = @session.room
        @theater = @room.theater
        @movie = @session.movie
    end

    def buy
        session = Session.find(params[:id])
        seats = params[:ticket_seats]

        selected_seats = []
        seats.keys.each do |seat|
            if params[:ticket_seats][seat] == "1"
                selected_seats << seat.split(",")
            end
        end

        basket = Basket.new
        basket.save

        selected_seats.each do |seat|
            Ticket.create(:session => session, :basket => basket, :row => seat[0], :seat => seat[1] )
        end

        redirect_to basket_path(basket)
    end
end

Soluções Web/Cinema/app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
  def index
    @theaters = Theater.all
  end

  def show
    @theater = Theater.find(params[:id])
    @theater_sessions = theater_sessions(@theater)
  end

  private
  def theater_sessions(theater)
    sessions = []

    rooms = Room.where(theater_id: theater.id)
    rooms.each do |room|
      room_sessions = Session.where(room_id: room.id)
      room_sessions.each do |session|
        sessions << session
      end
    end

    return sessions
  end
end

Soluções Web/Cinema/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

Soluções Web/Cinema/app/helpers/application_helper.rb
module ApplicationHelper
end

Soluções Web/Cinema/app/helpers/baskets_helper.rb
module BasketsHelper
end

Soluções Web/Cinema/app/helpers/movies_helper.rb
module MoviesHelper
end

Soluções Web/Cinema/app/helpers/rooms_helper.rb
module RoomsHelper
end

Soluções Web/Cinema/app/helpers/sessions_helper.rb
module SessionsHelper
end

Soluções Web/Cinema/app/helpers/theaters_helper.rb
module TheatersHelper
end

Soluções Web/Cinema/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Soluções Web/Cinema/app/views/admin/rooms/_form.html.erb
<%

url = admin_theater_rooms_path(@theater)

if @room.id
    url = admin_theater_room_path(@theater, @room)
end

%>
<%= form_for [:admin, @room] , url: url do |f| %>

    <% if @room.errors.any? %>
    <div id="error_explanation">
        <h2>
            <%= pluralize(@room.errors.count, "erro") %> impediram este cinema de ser incluído:
        </h2>
        <ul>
            <% @room.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
    <% end %>

    <p>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :rows %>
        <%= f.text_field :rows %>
    </p>

    <p>
        <%= f.label :seats_per_row %>
        <%= f.text_field :seats_per_row %>
    </p>

    <p><%= f.submit %></p>
<% end %>

Soluções Web/Cinema/app/views/admin/rooms/edit.html.erb
<h1>Alterando Sala do Cinema <%= @theater.name %></h1>

<%= render 'form' %>

<%= link_to 'Voltar', admin_theater_rooms_path %>

Soluções Web/Cinema/app/views/admin/rooms/index.html.erb
<h1>Salas pertencentes ao Cinema <%= @theater.name %></h1>

<% if @rooms.any? %>
<table>
    <tr>
        <th>Nome</th>
        <th colspan="3">&nbsp;</th>
    </tr>
    <% @rooms.each do |room| %>
    <tr>
        <td><%= room.name %></td>
        <td><%= link_to 'Visualizar', admin_theater_room_path(@theater, room) %></td>
        <td><%= link_to 'Editar', edit_admin_theater_room_path(@theater, room) %></td>
        <td><%= link_to 'Remover', admin_theater_room_path(@theater, room), method: :delete, data: { confirm: "Você está prestes a remover definitivamente esta sala.\nVocê tem certeza e deseja prosseguir com esta operação?" } %></td>
    </tr>
    <% end %>
</table>
<% end %>

<%= link_to 'Incluir nova', new_admin_theater_room_path %>

Soluções Web/Cinema/app/views/admin/rooms/new.html.erb
<h1>Incluir Nova Sala para o Cinema <%= @theater.name %></h1>

<%= render 'form' %>

<%= link_to 'Voltar', admin_theater_rooms_path %>

Soluções Web/Cinema/app/views/admin/rooms/show.html.erb
<h1>Exibindo Sala <%= @room.name %> do Cinema <%= @theater.name %></h1>

<% if @room.sessions.any? %>
<table>
    <tr>
        <th>Filme</th>
        <th>Data</th>
        <th>Hora</th>
    </tr>
    <%
        @room.sessions.each do |session|
            movie = Movie.find(session.movie)
    %>
    <tr>
        <td><%= movie.name %></td>
        <td><%= session.datetime.to_date.strftime("%d/%m/%Y") %></td>
        <td><%= session.datetime.to_time.strftime("%H:%M") %></td>
    </tr>
    <% end %>
</table>
<% end %>

<%= link_to 'Voltar', admin_theater_rooms_path(@theater) %> | <%= link_to 'Editar', edit_admin_theater_room_path(@theater, @room) %>

Soluções Web/Cinema/app/views/baskets/finished.html.erb
<h2>Compra Concluída - Resumo</h2>
<%
@basket.tickets.each do |ticket|
    session = ticket.session
    room = session.room
    theater = room.theater
    movie = session.movie
%>
<div class="ticket">
    <p><strong>Cinema:</strong> <%= theater.name %></p>
    <p><strong>Sala:</strong> <%= room.name %></p>
    <p><strong>Filme:</strong> <%= movie.name %></p>
    <p><strong>Data:</strong> <%= session.datetime.strftime("%d/%m/%Y") %></p>
    <p><strong>Hora:</strong> <%= session.datetime.strftime("%H:%M") %></p>
    <p><strong>Fileira:</strong> <%= ticket.row %></p>
    <p><strong>Assento:</strong> <%= ticket.seat %></p>
</div>

<%
end
%>

<%= link_to 'Voltar', theaters_path , class: "single button" %>

Soluções Web/Cinema/app/views/baskets/show.html.erb
<h2>Resumo da Compra</h2>
<%= form_for :basket do |f| %>
    <%
    @tickets.each do |ticket|
        session = ticket.session
        room = session.room
        theater = room.theater
        movie = session.movie
    %>
    <div class="ticket">
        <p><strong>Cinema:</strong> <%= theater.name %></p>
        <p><strong>Sala:</strong> <%= room.name %></p>
        <p><strong>Filme:</strong> <%= movie.name %></p>
        <p><strong>Data:</strong> <%= session.datetime.strftime("%d/%m/%Y") %></p>
        <p><strong>Hora:</strong> <%= session.datetime.strftime("%H:%M") %></p>
        <p><strong>Fileira:</strong> <%= ticket.row %></p>
        <p><strong>Assento:</strong> <%= ticket.seat %></p>
    </div>

    <%
    end
    %>
    <button class="button single" name="confirmed">Confirmar</button>
    <button class="button single" name="cancel">Cancelar</button>
<% end %>