Soluções Web/Cinema/config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  devise_for :users

  root to: 'welcome#index'

  resources :theaters do
    resources :rooms do
      resources :sessions
    end
    resources :sessions
  end

  resources :baskets, only: :show
  post '/baskets/:id', to: 'baskets#confirm'
  get '/baskets/:id/finished', to: 'baskets#finished'

  get '/movie/sessions/:id/choose_seat', to: 'sessions#choose_seat'
  post '/movie/sessions/:id/choose_seat', to: 'sessions#buy'

  namespace :admin do
    root 'welcome#index'

    resources :theaters do
      resources :rooms do
        resources :sessions
      end
    end

    resources :movies do
      resources :sessions
    end

    resources :sessions
  end
end

Soluções Web/Cinema/app/models/basket.rb
class Basket < ActiveRecord::Base
  belongs_to :customer
  has_many :tickets
end

Soluções Web/Cinema/app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Soluções Web/Cinema/app/models/movie.rb
class Movie < ActiveRecord::Base
    has_many :sessions
    validates :name , presence: true
    validates :summary , presence: true
    validates :debut , presence: true
end

Soluções Web/Cinema/app/models/room.rb
class Room < ActiveRecord::Base
    belongs_to :theater
    has_many :sessions
    validates :name , presence: true
    validates :rows , presence: true
    validates :seats_per_row , presence: true
end

Soluções Web/Cinema/app/models/session.rb
class Session < ActiveRecord::Base
  belongs_to :room
  belongs_to :movie
  has_many :tickets
  validates :datetime , presence: true
end

Soluções Web/Cinema/app/models/theater.rb
class Theater < ActiveRecord::Base
    has_many :rooms
    validates :name , presence: true , length: { minimum: 5 }
    validates :address , presence: true
    validates :address_number , presence: true
    validates :city , presence: true
    validates :state , presence: true
end

Soluções Web/Cinema/app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :session
  belongs_to :basket
end

Soluções Web/Cinema/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Soluções Web/Cinema/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Soluções Web/Cinema/app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  def show
    @basket = Basket.find(params[:id])
    @tickets = Ticket.where(basket: @basket.id)
  end

  def confirm
    if params[:confirmed].nil?
      basket = Basket.find(params[:id])
      basket.destroy

      redirect_to root_path
    elsif customer_signed_in?
      basket = Basket.find(params[:id])
      basket.customer = current_customer
      basket.save

      redirect_to "/baskets/" + basket.id.to_s + "/finished"
    else
      redirect_to new_customer_session_path
    end
  end

  def finished
    @basket = Basket.find(params[:id])
  end
end

Soluções Web/Cinema/app/controllers/movie_sessions_controller.rb
class MovieSessionsController < ApplicationController
    def choose_seat
        @session = movie_sessionsSession.find(params[:id])
        @room = @session.room
        @theater = @room.theater
        @movie = @session.movie
    end

    def buy
        session = Session.find(params[:id])
        seats = params[:ticket_seats]

        selected_seats = []
        seats.keys.each do |seat|
            if params[:ticket_seats][seat] == "1"
                selected_seats << seat.split(",")
            end
        end

        basket = Basket.new
        basket.save

        selected_seats.each do |seat|
            Ticket.create(:session => session, :basket => basket, :row => seat[0], :seat => seat[1] )
        end

        redirect_to basket_path(basket)
    end
end

Soluções Web/Cinema/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def choose_seat
        @session = Session.find(params[:id])
        @room = @session.room
        @theater = @room.theater
        @movie = @session.movie
    end

    def buy
        session = Session.find(params[:id])
        seats = params[:ticket_seats]

        selected_seats = []
        seats.keys.each do |seat|
            if params[:ticket_seats][seat] == "1"
                selected_seats << seat.split(",")
            end
        end

        basket = Basket.new
        basket.save

        selected_seats.each do |seat|
            Ticket.create(:session => session, :basket => basket, :row => seat[0], :seat => seat[1] )
        end

        redirect_to basket_path(basket)
    end
end

Soluções Web/Cinema/app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
  def index
    @theaters = Theater.all
  end

  def show
    @theater = Theater.find(params[:id])
    @theater_sessions = theater_sessions(@theater)
  end

  private
  def theater_sessions(theater)
    sessions = []

    rooms = Room.where(theater_id: theater.id)
    rooms.each do |room|
      room_sessions = Session.where(room_id: room.id)
      room_sessions.each do |session|
        sessions << session
      end
    end

    return sessions
  end
end

Soluções Web/Cinema/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

Soluções Web/Cinema/app/helpers/application_helper.rb
module ApplicationHelper
end

Soluções Web/Cinema/app/helpers/baskets_helper.rb
module BasketsHelper
end

Soluções Web/Cinema/app/helpers/movies_helper.rb
module MoviesHelper
end

Soluções Web/Cinema/app/helpers/rooms_helper.rb
module RoomsHelper
end

Soluções Web/Cinema/app/helpers/sessions_helper.rb
module SessionsHelper
end

Soluções Web/Cinema/app/helpers/theaters_helper.rb
module TheatersHelper
end

Soluções Web/Cinema/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Soluções Web/Cinema/app/views/customers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Entrar", new_session_path(resource_name), class: "button single span-2" %>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Cadastrar-se", new_registration_path(resource_name), class: "button single span-2" %>
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueci minha senha", new_password_path(resource_name), class: "button single span-2" %>
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Não recebi o email de confirmação", new_confirmation_path(resource_name) %>
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %>
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Entrar com #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %>
  <% end -%>
<% end -%>

Soluções Web/Cinema/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Entrar", new_session_path(resource_name), class: "button single span-2" %>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Cadastrar-se", new_registration_path(resource_name), class: "button single span-2" %>
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueci minha senha", new_password_path(resource_name), class: "button single span-2" %>
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Não recebi o email de confirmação", new_confirmation_path(resource_name) %>
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %>
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Entrar com #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %>
  <% end -%>
<% end -%>