Soluções Web/Cinema/config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  devise_for :users

  root to: 'welcome#index'

  resources :theaters do
    resources :rooms do
      resources :sessions
    end
    resources :sessions
  end

  resources :baskets, only: :show
  post '/baskets/:id', to: 'baskets#confirm'
  get '/baskets/:id/finished', to: 'baskets#finished'

  get '/movie/sessions/:id/choose_seat', to: 'sessions#choose_seat'
  post '/movie/sessions/:id/choose_seat', to: 'sessions#buy'

  namespace :admin do
    root 'welcome#index'

    resources :theaters do
      resources :rooms do
        resources :sessions
      end
    end

    resources :movies do
      resources :sessions
    end

    resources :sessions
  end
end

Soluções Web/Cinema/app/models/theater.rb
class Theater < ActiveRecord::Base
    has_many :rooms
    validates :name , presence: true , length: { minimum: 5 }
    validates :address , presence: true
    validates :address_number , presence: true
    validates :city , presence: true
    validates :state , presence: true
end

Soluções Web/Cinema/app/controllers/admin/theaters_controller.rb
class Admin::TheatersController < Admin::ApplicationController
    def index
        @theaters = Theater.all
    end

    def show
        @theater = Theater.find(params[:id])
    end

    def new
        @theater = Theater.new
    end

    def create
        @theater = Theater.new(theater_params)

        if @theater.save
            redirect_to @theater
        else
            render 'new'
        end
    end

    def edit
        @theater = Theater.find(params[:id])
    end

    def update
        @theater = Theater.find(params[:id])

        if @theater.update(theater_params)
            redirect_to @theater
        else
            render 'edit'
        end
    end

    def destroy
        @theater = Theater.find(params[:id])
        @theater.destroy
        redirect_to theaters_path
    end

    private
    def theater_params
        params.require(:theater).permit(:name, :address, :address_number, :city, :state)
    end
end

Soluções Web/Cinema/app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
  def index
    @theaters = Theater.all
  end

  def show
    @theater = Theater.find(params[:id])
    @theater_sessions = theater_sessions(@theater)
  end

  private
  def theater_sessions(theater)
    sessions = []

    rooms = Room.where(theater_id: theater.id)
    rooms.each do |room|
      room_sessions = Session.where(room_id: room.id)
      room_sessions.each do |session|
        sessions << session
      end
    end

    return sessions
  end
end

Soluções Web/Cinema/app/helpers/theaters_helper.rb
module TheatersHelper
end

Soluções Web/Cinema/app/views/admin/theaters/_form.html.erb
<%= form_for [:admin, @theater] do |f| %>

    <% if @theater.errors.any? %>
    <div id="error_explanation">
        <h2>
            <%= pluralize(@theater.errors.count, "erro") %> impediram este cinema de ser incluído:
        </h2>
        <ul>
            <% @theater.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
    <% end %>

    <p>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :address %>
        <%= f.text_field :address %>
    </p>

    <p>
        <%= f.label :address_number %>
        <%= f.text_field :address_number %>
    </p>

    <p>
        <%= f.label :city %>
        <%= f.text_field :city %>
    </p>

    <p>
        <%= f.label :state %>
        <%= f.text_field :state %>
    </p>

    <p><%= f.submit %></p>
<% end %>

Soluções Web/Cinema/app/views/admin/theaters/edit.html.erb
<h1>Alterando Cinema</h1>

<%= render 'form' %>

<%= link_to 'Voltar', admin_theaters_path %>

Soluções Web/Cinema/app/views/admin/theaters/index.html.erb
<h1>Cinemas</h1>

<% if @theaters.any? %>
<table>
    <tr>
        <th>Nome</th>
        <th>Endereço</th>
        <th>Cidade</th>
        <th>Estado</th>
        <th colspan="3">&nbsp;</th>
    </tr>
    <% @theaters.each do |theater| %>
    <tr>
        <td><%= theater.name %></td>
        <td><%= theater.address %>, <%= theater.address_number %></td>
        <td><%= theater.city %></td>
        <td><%= theater.state %></td>
        <td><%= link_to 'Visualizar', admin_theater_path(theater) %></td>
        <td><%= link_to 'Editar', edit_admin_theater_path(theater) %></td>
        <td><%= link_to 'Remover', admin_theater_path(theater), method: :delete, data: { confirm: "Você está prestes a remover definitivamente este cinema.\nVocê tem certeza e deseja prosseguir com esta operação?" } %></td>
    </tr>
    <% end %>
</table>
<% end %>

<%= link_to 'Incluir novo', new_admin_theater_path %>

Soluções Web/Cinema/app/views/admin/theaters/new.html.erb
<h1>Incluir Novo Cinema</h1>

<%= render 'form' %>

<%= link_to 'Voltar', admin_theaters_path %>

Soluções Web/Cinema/app/views/admin/theaters/show.html.erb
<h1>Exibindo Cinema: <%= @theater.name %></h1>

<p>
    <strong>Endereço:</strong>
    <%= @theater.address %>, <%= @theater.address_number %>
</p>

<p>
    <strong>Cidade:</strong>
    <%= @theater.city %>
</p>

<p>
    <strong>Estado:</strong>
    <%= @theater.state %>
</p>

<h2>Salas</h2>
<% @theater.rooms.each do |room| %>
    <p>
        <strong>Nome:</strong> <%= room.name %> (Capacidade: <%= room.seats_per_row * room.rows %> lugares) <%= link_to 'Ver Sessões' , admin_theater_room_sessions_path(@theater, room) %>
    </p>
<% end %>

<%= link_to 'Voltar', admin_theaters_path %> | <%= link_to 'Editar', edit_admin_theater_path(@theater) %> | <%= link_to 'Editar Salas', admin_theater_rooms_path(@theater) %>