Soluções Web/Cinema/config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  devise_for :users

  root to: 'welcome#index'

  resources :theaters do
    resources :rooms do
      resources :sessions
    end
    resources :sessions
  end

  resources :baskets, only: :show
  post '/baskets/:id', to: 'baskets#confirm'
  get '/baskets/:id/finished', to: 'baskets#finished'

  get '/movie/sessions/:id/choose_seat', to: 'sessions#choose_seat'
  post '/movie/sessions/:id/choose_seat', to: 'sessions#buy'

  namespace :admin do
    root 'welcome#index'

    resources :theaters do
      resources :rooms do
        resources :sessions
      end
    end

    resources :movies do
      resources :sessions
    end

    resources :sessions
  end
end

Soluções Web/Cinema/app/models/basket.rb
class Basket < ActiveRecord::Base
  belongs_to :customer
  has_many :tickets
end

Soluções Web/Cinema/app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Soluções Web/Cinema/app/models/movie.rb
class Movie < ActiveRecord::Base
    has_many :sessions
    validates :name , presence: true
    validates :summary , presence: true
    validates :debut , presence: true
end

Soluções Web/Cinema/app/models/room.rb
class Room < ActiveRecord::Base
    belongs_to :theater
    has_many :sessions
    validates :name , presence: true
    validates :rows , presence: true
    validates :seats_per_row , presence: true
end

Soluções Web/Cinema/app/models/session.rb
class Session < ActiveRecord::Base
  belongs_to :room
  belongs_to :movie
  has_many :tickets
  validates :datetime , presence: true
end

Soluções Web/Cinema/app/models/theater.rb
class Theater < ActiveRecord::Base
    has_many :rooms
    validates :name , presence: true , length: { minimum: 5 }
    validates :address , presence: true
    validates :address_number , presence: true
    validates :city , presence: true
    validates :state , presence: true
end

Soluções Web/Cinema/app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :session
  belongs_to :basket
end

Soluções Web/Cinema/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Soluções Web/Cinema/app/controllers/admin/movies_controller.rb
class Admin::MoviesController < Admin::ApplicationController
    def index
        @movies = Movie.all
    end

    def show
        @movie = Movie.find(params[:id])
    end

    def new
        @movie = Movie.new
    end

    def create
        @movie = Movie.new(movie_params)
        if @movie.save
            redirect_to @movie
        else
            render 'new'
        end
    end

    def edit
        @movie = Movie.find(params[:id])
    end

    def update
        @movie = Movie.find(params[:id])

        if @movie.update(movie_params)
            redirect_to movies_path
        else
            render 'edit'
        end
    end

    private
    def movie_params
        params.require(:movie).permit(:name, :summary, :debut)
    end
end

Soluções Web/Cinema/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Soluções Web/Cinema/app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  def show
    @basket = Basket.find(params[:id])
    @tickets = Ticket.where(basket: @basket.id)
  end

  def confirm
    if params[:confirmed].nil?
      basket = Basket.find(params[:id])
      basket.destroy

      redirect_to root_path
    elsif customer_signed_in?
      basket = Basket.find(params[:id])
      basket.customer = current_customer
      basket.save

      redirect_to "/baskets/" + basket.id.to_s + "/finished"
    else
      redirect_to new_customer_session_path
    end
  end

  def finished
    @basket = Basket.find(params[:id])
  end
end

Soluções Web/Cinema/app/controllers/movie_sessions_controller.rb
class MovieSessionsController < ApplicationController
    def choose_seat
        @session = movie_sessionsSession.find(params[:id])
        @room = @session.room
        @theater = @room.theater
        @movie = @session.movie
    end

    def buy
        session = Session.find(params[:id])
        seats = params[:ticket_seats]

        selected_seats = []
        seats.keys.each do |seat|
            if params[:ticket_seats][seat] == "1"
                selected_seats << seat.split(",")
            end
        end

        basket = Basket.new
        basket.save

        selected_seats.each do |seat|
            Ticket.create(:session => session, :basket => basket, :row => seat[0], :seat => seat[1] )
        end

        redirect_to basket_path(basket)
    end
end

Soluções Web/Cinema/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def choose_seat
        @session = Session.find(params[:id])
        @room = @session.room
        @theater = @room.theater
        @movie = @session.movie
    end

    def buy
        session = Session.find(params[:id])
        seats = params[:ticket_seats]

        selected_seats = []
        seats.keys.each do |seat|
            if params[:ticket_seats][seat] == "1"
                selected_seats << seat.split(",")
            end
        end

        basket = Basket.new
        basket.save

        selected_seats.each do |seat|
            Ticket.create(:session => session, :basket => basket, :row => seat[0], :seat => seat[1] )
        end

        redirect_to basket_path(basket)
    end
end

Soluções Web/Cinema/app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
  def index
    @theaters = Theater.all
  end

  def show
    @theater = Theater.find(params[:id])
    @theater_sessions = theater_sessions(@theater)
  end

  private
  def theater_sessions(theater)
    sessions = []

    rooms = Room.where(theater_id: theater.id)
    rooms.each do |room|
      room_sessions = Session.where(room_id: room.id)
      room_sessions.each do |session|
        sessions << session
      end
    end

    return sessions
  end
end

Soluções Web/Cinema/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

Soluções Web/Cinema/app/helpers/application_helper.rb
module ApplicationHelper
end

Soluções Web/Cinema/app/helpers/baskets_helper.rb
module BasketsHelper
end

Soluções Web/Cinema/app/helpers/movies_helper.rb
module MoviesHelper
end

Soluções Web/Cinema/app/helpers/rooms_helper.rb
module RoomsHelper
end

Soluções Web/Cinema/app/helpers/sessions_helper.rb
module SessionsHelper
end

Soluções Web/Cinema/app/helpers/theaters_helper.rb
module TheatersHelper
end

Soluções Web/Cinema/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Soluções Web/Cinema/app/views/admin/movies/_form.html.erb
<%= form_for [:admin, @movie] do |f| %>

    <% if @movie.errors.any? %>
    <div id="error_explanation">
        <h2>
            <%= pluralize(@movie.errors.count, "erro") %> impediram este filme de ser incluído:
        </h2>
        <ul>
            <% @movie.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
    <% end %>

    <p>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :summary %>
        <%= f.text_area :summary %>
    </p>

    <p>
        <%= f.label :debut %>
        <%= f.date_field :debut %>
    </p>

    <p><%= f.submit %></p>
<% end %>

Soluções Web/Cinema/app/views/admin/movies/edit.html.erb
<h1>Alterando Filme</h1>

<%= render 'form' %>

<%= link_to 'Voltar', admin_movies_path %>

Soluções Web/Cinema/app/views/admin/movies/index.html.erb
<h1>Filmes</h1>

<% if @movies.any? %>
<table>
    <tr>
        <th>Nome</th>
        <th>Estreia</th>
        <th colspan="3">&nbsp;</th>
    </tr>
    <% @movies.each do |movie| %>
    <tr>
        <td><%= movie.name %></td>
        <td><%= movie.debut.to_date.strftime("%d/%m/%Y") %></td>
        <td><%= link_to 'Visualizar', admin_movie_path(movie) %></td>
        <td><%= link_to 'Editar', edit_admin_movie_path(movie) %></td>
        <td><%= link_to 'Remover', admin_movie_path(movie), method: :delete, data: { confirm: "Você está prestes a remover definitivamente este filme.\nVocê tem certeza e deseja prosseguir com esta operação?" } %></td>
    </tr>
    <% end %>
</table>
<% end %>

<%= link_to 'Incluir novo', new_admin_movie_path %>

Soluções Web/Cinema/app/views/admin/movies/new.html.erb
<h1>Incluir Novo Filme</h1>

<%= render 'form' %>

<%= link_to 'Voltar', admin_movies_path %>

Soluções Web/Cinema/app/views/admin/movies/show.html.erb
<h1>Exibindo Filme: <%= @movie.name %></h1>

<p>
    <strong>Sinopse:</strong>
    <%= @movie.summary %>
</p>

<p>
    <strong>Estreia:</strong>
    <%= @movie.debut.to_date.strftime("%d/%m/%Y") %>
</p>

<% if @movie.sessions.any? %>
<table>
    <tr>
        <th>Cinema</th>
        <th>Sala</th>
        <th>Data</th>
        <th>Hora</th>
    </tr>
    <%
        @movie.sessions.each do |session|
            room = Room.find(session.room)
            theater = Theater.find(room.theater)
    %>
    <tr>
        <td><%= theater.name %></td>
        <td><%= room.name %></td>
        <td><%= session.datetime.to_date.strftime("%d/%m/%Y") %></td>
        <td><%= session.datetime.to_time.strftime("%H:%M") %></td>
    </tr>
    <% end %>
</table>
<% end %>

<%= link_to 'Voltar', admin_movies_path %> | <%= link_to 'Editar', edit_admin_movie_path(@movie) %> | <%= link_to 'Editar Sessões', admin_movie_sessions_path(@movie) %>